# Generated by Django 5.0.2 on 2024-02-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Marka Adı")),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Kategori Adı")),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Renk Adı")),
                ("code", models.CharField(max_length=50, verbose_name="Renk Kodu")),
            ],
        ),
        migrations.CreateModel(
            name="Filter_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        choices=[
                            ("0- 1000", "1000-2000"),
                            ("2000-3000", "3000-4000"),
                            ("4000-5000", "5000-6000"),
                            ("6000-7000", "7000-8000"),
                            ("8000-9000", "9000-10000"),
                        ],
                        max_length=60,
                        verbose_name="Fiyat Aralığı",
                    ),
                ),
            ],
        ),
    ]
