# Generated by Django 5.0.2 on 2024-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Kategori", "verbose_name_plural": "Kategoriler"},
        ),
        migrations.AddField(
            model_name="categories",
            name="slug",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
