# Generated by Django 5.0.2 on 2024-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeApp", "0002_alter_categories_options_categories_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AddField(
            model_name="filter_price",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
    ]
