# Generated by Django 5.0.2 on 2024-02-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeApp", "0004_alter_brand_options_alter_color_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Ürün Kodu",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="Ürün Resmi"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ürün Adı")),
                ("price", models.IntegerField(verbose_name="Fiyat")),
                (
                    "condition",
                    models.BooleanField(
                        choices=[("NEW", "Yeni"), ("OLD", "Eski")],
                        default=True,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "information",
                    models.TextField(blank=True, null=True, verbose_name="Bilgi"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "stock",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Mevcut"),
                            ("NOT AVAILABLE", "Mevcut Değil"),
                        ],
                        max_length=60,
                        verbose_name="Stok Durumu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Publish", "Aktif"), ("Draft", "Pasif")],
                        default="Publish",
                        max_length=200,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeApp.brand",
                        verbose_name="Marka",
                    ),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeApp.categories",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="storeApp.color",
                        verbose_name="Renk",
                    ),
                ),
                (
                    "filter_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeApp.filter_price",
                        verbose_name="Fiyat Aralığı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
            },
        ),
    ]
