# Generated by Django 5.0.2 on 2024-02-11 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storeApp", "0007_alter_product_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="condition",
        ),
    ]
