# Generated by Django 5.0.2 on 2024-02-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeApp", "0010_alter_product_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[("New", "Yeni"), ("OLD", "Eski")],
                default="Yeni",
                max_length=200,
                verbose_name="Ürün Durumu",
            ),
        ),
    ]
