# Generated by Django 5.0.2 on 2024-02-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeApp", "0011_alter_product_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter_price",
            name="price",
            field=models.CharField(
                choices=[
                    ("0- 1000", "1000-2000"),
                    ("2000-3000", "3000-4000"),
                    ("4000-5000", "5000-6000"),
                    ("6000-7000", "7000-8000"),
                    ("8000-9000", "9000-10000"),
                    ("10000 - ∞", "∞ - ∞"),
                ],
                max_length=60,
                verbose_name="Fiyat Aralığı",
            ),
        ),
    ]
