# Generated by Django 5.0.2 on 2024-02-15 17:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storeApp", "0012_alter_filter_price_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Ürün Açıklaması"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="information",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Ürün Bilgisi"
            ),
        ),
    ]
