# Generated by Django 5.0.2 on 2024-02-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeApp", "0013_alter_product_description_alter_product_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="İsim")),
                ("email", models.EmailField(max_length=200, verbose_name="E-Posta")),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("message", models.TextField(verbose_name="Mesaj")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Tarih")),
            ],
            options={
                "verbose_name": "İletişim",
                "verbose_name_plural": "İletişimler",
            },
        ),
    ]
