# Generated by Django 5.0.2 on 2024-02-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeApp", "0015_order_cartorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.CharField(
                choices=[("Paid", "Ödendi"), ("Not Paid", "Ödenmedi")],
                default="Ödenmedi",
                max_length=200,
                verbose_name="Ödeme Durumu",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Ödeme ID"
            ),
        ),
    ]
